version: "2"

issues:
  max-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - govet
